sku_names=['B&H SW 20HL',
            'B&H BG 20HL',
            'JPGL 20HL',
            'CAP 20HL',
            'SRF 20HL',
            'SRN 20HL',
            'PL 20HL',
            'DB 20HL',
            'SRF 10HL',
            'SRN 10HL',
            'DB 10HL',
            'DBST 20HL',
            'DBST 10HL',
            'B&H SF 20HL',
            'JP SP 20HL',
            'B&H SF 12HL',
            'JPGL 12HL',
            'B&H BG 12HL',
            'JP SW 20HL',
            'HWD 20HL',
            'HWD 10HL',
            'B&H PT 20HL',
            'RG 20HL',
            'RG 10HL',
            'RN 20HL',
            'RN 10HL',
            'RLS 20HL',
            'RLS 10HL',
            'DBLP 20HL',
            'DBLP 10HL',
            'HWLP 20HL',
            'DBLP 2 20HL',
            'DBLP 2 10HL',
            'PLLP 2 20HL',
            'B&H SF BOPP 20s',
            'B&H BG BOPP 20s',
            'B&H SW BOPP 20s',
            'JPGL HE 20HL',
            'LS SS 20HL',
            'LS CC 20HL',
            'Alchemy Mix1',
            'Alchemy 7MG',
            'LS OG 20HL',
            'FLG 20HL',
            'FLG 10HL']
sku_merged=[s.replace(" ",'') for s in sku_names]